export default function kearon() {
    return text;
}

const text = `Lyman Wight looked with pride upon his father’s military service during the American Revolution. To Wight, American victory in that conflict had done more than secure independence for the United States; it had secured rights to life and liberty for the American people. Wight believed those values were the lasting legacy of the American Revolution and enlisted to fight in the War of 1812 to protect them.

However, Wight’s optimistic perception of these American ideals was severely challenged by his experiences as a Church member living in Missouri during the 1830s. When he and more than one thousand other Latter-day Saints moved to Jackson County, Missouri, between 1831 and 1832, many residents of the county disliked Latter-day Saint beliefs and feared their potential influence on local politics. But rather than honor the rights of Church members to worship and vote according to the dictates of their own consciences, Jackson County residents used extralegal violence to force the Saints to either forsake their faith or leave the county. Acting as vigilantes, these Missouri citizens physically abused Church members living in the county, destroyed their property, and eventually ordered them to leave.

Wight was dismayed that officials in the state and federal governments would condone and even encourage such actions against members of the Church. In a petition to the United States Senate several years later, he would declare that his “father was a revolutiona[ry] soldier” and that these violations of Church members’ citizenship rights “[were] not the liberties he [gave] for me and my posterity.” Wight’s petition revealed a tension between the loyalty he felt to his country, his disdain for the actions of many of the men elected to govern that country, and his devotion to a faith he believed would outlast all earthly governments.

Redress
Like Lyman Wight, Church leaders had a complicated relationship with both the local and national governments. When members of the Church in Jackson County were driven from their homes in November 1833, Church leaders believed that the governments of Missouri and the United States had each failed to protect the citizenship rights of the Missouri Saints and felt compelled to protest the actions (and inaction) of elected officials that led to the Saints’ expulsion. At the same time, they began to make legal and political appeals to these same governments for the restoration of their property and citizenship rights in Jackson County.

A few prominent citizens were sympathetic to the plight of the Saints, but many were suspicious of the Saints’ motives. The Church’s commitment to the authority of revelation and the rapid gathering of Church members in Ohio and Missouri raised concerns among some Americans that the Church aimed to establish its own society that ignored the laws and authority of the United States. How could Church leaders protest their mistreatment by government while also expressing their support for government and even petitioning the government for assistance?

The Declaration
On August 17, 1835, in the midst of the Saints’ attempts to petition the government for help, Oliver Cowdery and Sidney Rigdon presented a document titled “Declaration of Government and Law” to Church members in Kirtland, Ohio. The declaration—now Doctrine and Covenants 134—sought to address all of the Saints’ concerns. By stating that “governments were instituted of God for the benefit of man” and that God would hold individuals “accountable for their acts” as government officials, the declaration described civil governments as secular institutions whose actions had spiritual consequences. By explaining that every government official “should be honored in his station” and “that to the laws all men owe respect and deference,” the declaration emphasized the Church’s teachings that its members should be law-abiding citizens who contribute to the “peace and harmony” of the societies in which they reside. It insisted that the government should secure the right of its citizens to worship according to the dictates of their own consciences and that religious groups experiencing abuse because of their religious practices were justified in petitioning the government for redress. Indirectly addressing the Saints’ recent experiences in Jackson County, the declaration insisted on the right of citizens to defend themselves against religious persecution if the government was unresponsive to their appeals for help.

Church members accepted the declaration and included it in the first edition of the Doctrine and Covenants. Unlike other sections of that book in which God revealed His will to the Saints, this section consisted of the Saints explaining their perspective and beliefs to the general public. It was most likely authored by Oliver Cowdery, as he had written on many of the topics it addressed in recent newspaper editorials. Although Joseph Smith was away in Michigan Territory when the declaration was presented to the Church, he accepted it and referenced it later in his speaking and writing.

How the Declaration Was Used
Especially after 1838, when the Saints were driven out of Missouri by the governor’s executive order, Joseph and other Church leaders invoked the declaration’s principles as they fought for Church members’ citizenship rights. For example, in 1840 while Joseph was in the eastern United States petitioning the federal government for redress after the confiscation of Church members’ property in Missouri, he wrote a letter to the editor of a Pennsylvania newspaper in which he answered claims made by some of the Church’s detractors in that area. In composing the letter, however, Joseph simply copied the text of the declaration on government, substituting “I believe” in every instance where the declaration contained the phrase “we believe.”

A few months later, Joseph, Sidney Rigdon, and Elias Higbee secured a hearing before a committee of United States senators to address the Missouri persecutions. In that hearing, Congressman John Jameson of Missouri tried to justify past violence against Church members by claiming that Joseph had given his followers liberty to ignore the laws of the land. Elias Higbee adamantly denied this claim, arguing that the Church “held to no such doctrine nor believed in any such thing,” and directed the committee to the 1835 “Declaration of Government and Law” in the Doctrine and Covenants as proof that they “had published long ago [their] belief on that subject.” This 1840 Senate committee declined to grant the Church redress for their persecutions, but Church leaders held to the values described in the declaration.

Two years later, when Church leaders wrote the now-famous “Wentworth Letter” as a brief description of the Church’s history and beliefs, the principles set forth in the declaration on government appear to have inspired the content of two different statements. Those statements, now known respectively as the eleventh and twelfth articles of faith, affirm the Church’s stance on the freedom of all men and women to worship God according to the dictates of their own conscience and its teachings that Church members are subject to government officials and should be obedient to the laws of the land in which they reside.

Render unto Caesar
Church leaders in the 1830s had to navigate a complicated political landscape, but their situation was hardly unprecedented. Religious groups seeking to establish a kingdom of God on earth have always needed to interact carefully with secular “powers that be.” Jesus Christ faced similar challenges during His mortal ministry. When He was accused of trying to usurp political power from Jewish and Roman officials, He declared that His “kingdom is not of this world” and directed His disciples to “render therefore unto Caesar the things which are Caesar’s; and unto God the things that are God’s.” In this sense, the 1835 “Declaration of Government and Law” echoed Jesus’s approach to building up His Church within the borders of sovereign nations.

“I volunteered to defend my [cou]ntry in the last war [the War of 1812],” Lyman Wight wrote in an 1839 petition to the United States Senate, “yet I [cannot live] in the State of Missouri without de[nying my] religion.” And so the self-proclaimed patriot lamented that he did not “feel satisfied to live [in s]uch bondage in what is called a free government.” Wight’s petition epitomized one of the primary principles in the “Declaration of Government and Law”—that Church members owe allegiance to their country but should simultaneously work to build governments that secure the liberty and rights of all citizens.`