export default function kearon() {
    return text;
}

const text = `As I struggled with “Federal... Emergency...,” my friend said, “No, it’s ‘Find Every Mormon Available.’” It was said in jest, but more than once media has reported that the first two groups at the scene were the Mormons and the Latter-day Saints — reminding us of the uphill task we have to be known by our full name. The point is, our people do go out of their way, a very long way out of their way, to help in crises the world over. This isn’t only disaster response and assisting refugees. These devoted souls are there in those often invisible, private, chronic situations which can last a lifetime. And of course, it’s not just our people; we work alongside representatives of numerous other faiths, often partnering with them in some of the most challenging parts of the world. There are certainly those involved doing extraordinary work for whom faith is not a driving force. But these contributions with our fellow believers are vast. And, importantly in today’s context, they are often overlooked. Part of that is our own fault, as we can have something of a tortured relationship with the idea of telling people about these good works. As a church, we are torn between having these efforts be private and letting that light shine in a way that will create awareness that we take our responsibility of contributing to society very seriously. We will probably need to talk more openly about these contributions, letting people know that at the heart of our faith is the desire to help our fellow human beings, wherever they are, people of faith and no faith at all. And that we do so without seeking converts in these most trying moments in people’s lives.
We need to help many more young people see the opportunities the free exercise of religion provides to serve others in need and unite communities in ways that benefit all people. And we need to help them understand that the expression of religious belief through community service is dependent on religious freedom. With this understanding, they will not only value religious freedom more deeply but will courageously act to strengthen and perpetuate it. Influencing society always seems to be the job of someone else — someone with more power, more money, more time. Perhaps we expect some program or sponsor to take the lead. But when it comes to taking care of people, there is no “someone else”; there is only us. Civic engagement requires people to freely act on their beliefs and solve the problems of their communities. If the prevailing philanthropic desires of our rising generation are to be harnessed and maximized, our young people will need to come to the same conclusion as have so many of us here today. And that is, that this is the most worthy of causes — a spring and holiest beliefs, and at the same time, blesses individuals, families, communities of all descriptions and entire nations. How to unite these benevolent desires of the rising generation with the responsibility of preserving religious freedom, along with every other inalienable right, is the task before all of us, and I am so grateful that you have gathered in this way to address just that.
We have a responsibility to help and, as God told the Prophet Jeremiah, “seek the welfare of the city where I have sent you into exile, and pray to the Lord on its behalf, for in its welfare you will find your welfare.”11
Conclusion
Now to conclude, every society has a foundation of truths, rules, expectations and norms which guide their thinking and their actions every day. Many take them for granted. And like all things we suppose will simply always be there for us — like the air we breathe — we hardly notice them. That is, until they’re challenged. And then we have to look closely and really get to know them, as if discovering them for the first time. So it is with religious freedom.
The way we all as human beings form our deepest beliefs is perhaps life’s greatest journey of discovery. The freedom in which we do so is precious. Our ability to practice and share those beliefs as we learn of and come to understand the beliefs of others enriches us all, broadens our view and creates harmony. A climate in which we are free to believe and practice is also a climate in which we can contribute. Religious freedom demands both the universal right and the universal responsibility, and it is our turn to do our part.
As human beings and the children of divine creation, we all want to live by a moral vision and want to share it with others. In doing this, we enter the realm of both religion and politics. This can be messy and contentious, but we have reason to be optimistic. As Martin Luther King Jr. was so fond of saying, drawing from the abolitionist Theodore Parker, “The arc of the moral universe is long, but it bends toward justice.”12
We are in that arc, and God expects us to do our part in nudging it toward justice. This is our work. Thank you.`