export default function myText() {
    return text;
}

const text = `Setting Priorities and Seeking Peace
In my view, those of us who care deeply about religious freedom have two important responsibilities if we want to also be peace- makers. First, we must set priorities, so we are clear about what is core to religious freedom and what is less vital. Only then can we understand where compromises can be struck. Second, we must learn how to get involved politically, socially, and professionally to both defend religious freedom as a fundamental right and to make appropriate compromises in the interest of fairness to others and peace. I want to touch on both these responsibilities.
First, setting religious freedom priorities. Some may be shocked to hear this, but not all religious freedoms are equally important. This is an obvious point, but it is an important one for clear thinking. If you had to make a choice, for example, between the freedom to pray with your family in your home and the freedom to hire only people of your own faith in your big business, I think it’s obvious which one you would choose. While both involve religious liberty, one is more essential than the other. Although it can limit the free exercise of religion, barring big business owners from hiring only people of their own faith has been the law for decades. But barring someone from praying in his own home would be an intolerable act of tyranny.
So, in a pluralistic nation where religious people and institutions find themselves competing for influence with others having much different priorities and interests, sometimes we have to make hard choices. We have to prioritize. Defenders of religious freedom have to decide what is closer to the essential core of religious freedom and what is more peripheral. To do otherwise risks weakening our defense of what is essential. If everything that could even loosely be considered “religious” is treated as equally important, then effectively nothing religious is important.
The innermost core.
Let’s talk, then, about what rights are at the innermost core of religious freedoms. Here our constitutional and legal traditions provide some guidance. Courts have long recognized the need for greater protections for private and intimate matters than for public or commercial ones. That make sense, and it provides a starting point for thinking about religious freedom priorities. As a general matter, religious liberty claims are more compelling the more closely they relate to purely private, family, and ecclesiastical matters, and, conversely, less compelling the closer they get to public and governmental functions. There may be exceptions, but that’s a good starting point when thinking about religious freedom priorities and potential compromises.
Certain freedoms are at the core of religious liberty because they lie within a fundamentally private sphere. On these freedoms there is little room for compromise. They include freedom of belief; freedoms related to family gospel teaching and worship; freedom to express your beliefs to another willing listener, such as in missionary work; and freedoms related to the internal affairs of churches, including the establishment of Church doctrine, the selection and regulation of priesthood leadership, and the determination of membership criteria. These religious freedoms fall within a zone of personal and institutional autonomy and thus are subject to little if any regulation by government. They are basically nonnegotiable.
The inner core includes more than just private matters. Believers are entitled to the same rights of free speech and expression in the public square as nonbelievers. That means they have the same First Amendment right as any other citizen to express their views on public streets and sidewalks; to publish their beliefs via print, radio, the Internet, and social media; to participate fully in democratic debates over matters of public policy, including controversial matters; and to petition the government for protection of their interests. These are basic freedoms inherent in American citizenship and are likewise nonnegotiable.
The inner core also includes the right not to be punished, retaliated against, or discriminated against by government based on religion. No believer should be excluded from public office or employment based solely on their faith. America doesn’t have religious tests for governmental positions. Similarly, there should be no religious test for working in the various professions regulated by government. For example, those with traditional beliefs regarding marriage, family, gender, and sexuality should not be excluded from being professional counselors, teachers, lawyers, doctors, and any other category of occupation where the government grants licenses. Nor should it be more difficult to establish a nonprofit religious organization than a secular nonprofit. And religious organizations should not be denied nonprofit status based on their doctrines and religious practices. Again, these basic rights to equal treatment are fundamental American freedoms and should not be open for discussion or compromise.
What I’ve just described may be called the inner core of religious freedom. Unless that core is strongly protected, there is no religious freedom as Americans have known it. These freedoms are essential to individual believers and their families in their private lives. They are also essential to prevent official persecution and to ensure that members of particular faith communities are not rendered legal and social outcasts, as Jews once were in Europe.
Near the core
Close to this innermost core are freedoms that pertain to religiously important nonprofit functions carried on by religious organizations. This includes the freedom of religious nonprofits to have employment policies that reflect their religious beliefs, including the freedom to hire based on religious criteria. This is the freedom, enshrined in Title VII, that allows the Church to have a temple recommend standard for Church employment. Without this freedom, the ability of religious organizations to carry out their missions would be severely impaired.
Also in this category is the right to establish religious schools, colleges, and universities. Such institutions should have the freedom to establish student honor codes that reflect their religious teachings, including standards governing sexually appropriate conduct. And government should not use its ability to fund education to coerce or pressure religious schools into abandoning their religious standards.
Likewise, religious charities should have the right to conduct their good works according to the dictates of their respective faiths— without substantial interference by government and without being forced to engage in activities that are fundamentally contrary to their beliefs.
These freedoms are vitally important to the Church and other religious organizations. But as you can tell, they already get us into areas that are increasingly controversial because sometimes they can extend beyond the purely private or religious.
Moving beyond the core
As we move to more commercial settings, our expectations of unfettered religious freedom must be tempered. This is not because commerce is unimportant but because it is now heavily regulated and overlaps with what for decades have been considered civil rights—such as the right not to be discriminated against in employment or denied service at a public accommodation based on certain characteristics.
Claims by business owners for religious freedom are strongest in small, intimate, and family business settings and correspondingly weaker in large and impersonal corporate settings. Still, businesses should not be forced to produce products or types of services that fundamentally conflict with their religious beliefs. For instance, no one could seriously contend that a business should be required to print or distribute pornography; that principle can also apply in less obvious circumstances as well. Similarly, businesses should be able to use symbols and messages that reflect their beliefs. I understand that In-N-Out Burger prints “John 3:16” on the bottom of every cup.
But the ability of secular businesses to deny employment or services to those whose lifestyles they consider immoral will often be limited. While In-N-Out Burger should have the right to put scriptural messages on its cups, it cannot expect to refuse service to non-Christians or LGBT persons.
Hence, the commercial setting is an area where defenders of religious freedom sometimes must be willing to make prudential compromises. Not every aspect of your business will be able to reflect your religious beliefs in the same way your home or religious congregation can. Preserving the ability of business owners to conduct every aspect of their businesses according to their religious beliefs will be impossible. And the Church itself is not in a position to fight that fight if doing so comes at the expense of more core religious freedoms. Protecting those core freedoms must remain the priority, or we risk losing even them.
The outer circle
Finally, there are zones where claims for religious freedom are much weaker and will be very difficult to defend. Some of these pertain to government services, where officials are required by law to perform certain functions. In these areas, religious beliefs should be reasonably accommodated, but other governmental interests may significantly limit the degree of accommodation. For instance, if it is your job to perform marriages for the county clerk’s office and no one else can easily take your place, then your freedom to refuse to perform marriages that are contrary to your religious beliefs may be very limited.
Still, a government that respects religious liberty should accommodate the religious needs of its civil servants to the greatest extent reasonable. Appropriate accommodations should also be made for religious dress and, where possible, Sabbath observance.
In summary, as I see things, there is a hierarchy of religious freedoms and we have no choice but to set priorities. Those that relate to private and ecclesiastical contexts or are part of the basic rights of all citizens, are the most essential and least subject to compromise, while those that relate to commercial and governmental settings will of necessity require greater pragmatism and compromise. Please understand that in labeling some freedoms part of the “core” of religious liberty, I am not suggesting that freedoms outside that core are unimportant or not worth defending. What I am suggesting is that if we want to preserve religious freedom and live in peace in a society that is increasingly intolerant of faith, then we will have to be very clear about what matters most and make wise compromises in areas that matter less, because if we don’t, we risk losing essential rights that we simply cannot live without.
Defending Religious Freedom—Lift Where You Stand
I said earlier that those who care about religious freedom must first set priorities and then, second, learn how to get involved to defend religious freedom and make appropriate compromises in the interest of fairness and peace. I turn now to this second imperative—how to get involved in the defense of religious freedom.
Recently Elder Christofferson spoke at the Freedom Festival here in Provo about how ordinary citizens can defend religious freedom. He outlined a simple four-part approach that applies to all of us:
First, become informed. You are doing that today and throughout this conference. To defend religious freedom, we need wisdom— indeed, inspired wisdom. And that requires knowledge. So it is vital that we become informed about what religious freedom means; what freedoms are most essential; what competing social interests exist; how society and our friends, neighbors, and children view religious freedom; what challenges religious freedom faces; and how those challenges will affect real people living real lives. We must become informed.
Second, learn to speak up with courage and civility. This is a fine line. On the one hand, we cannot be intimidated into silence by intolerant voices that claim to represent progress and open-mindedness. That tired bromide is getting old; such voices do not represent progress, and we cannot allow it to silence us. But by the same token, we must state our views with genuine civility. This isn’t the time for anger. So, when you speak up, speak calmly. Smile a bit. Seek true understanding. Acknowledge legitimate points. And explain why the freedoms you defend are so important to you, your family, and your church—make it personal. Stand firmly for principle while understanding that in some areas we will have to compromise to protect our most vital freedoms.
Third, as President Uchtdorf would say, “Lift where you stand.”9 You don’t need to run for Congress or the legislature to make a difference. And the Church doesn’t need you to undertake lawsuits on its behalf. What is needed is for you to get involved in the political, community, professional, and business organizations around you and to express your concern and support for religious freedom. The time for an insular focus on just our own families and congregations is gone. We have to get involved in the community organizations around us and encourage them to be respectful and supportive of religious freedom, even when that means accommodating to some extent beliefs and practices we don’t like.
Finally, at all times, be an example of the believers so that others will see your good works, experience your genuine friendship, and be sympathetic toward your concerns about religious freedom. As Elder Christofferson said:
“Americans tend to respect and protect what they believe is good. So let us show them the highest and best in our faiths—our willingness to love and serve others, to build strong families, to live honorable lives, to be good citizens. As our fellow citizens see the good- ness of your faith, ‘they will want to listen to you and understand when you say your religious freedom is being abridged. They may not agree with you, or even understand entirely the issue that is so important to you. But if they know you and respect you because you are a true [example of the believers], they will be far more inclined to work toward a solution that respects [essential] religious freedoms.’ ”10
Compromises
Finally, some thoughts on compromises. As we face difficult social and legal issues, where other interests are competing with religious freedom, we need to be prepared to make wise compromises in areas that, although important, may not be core to religious freedom. Frankly, we have no choice. When such conflicts arise, we should think in terms of “fairness for all,” a phrase the Church has used in a number of settings.
What does “fairness for all” mean? At bottom, it means that every person—including people of faith and their religious communities—should have enough space to live according to their core beliefs so long as they don’t harm the fundamental rights of others. It means pluralism. It means a fair opportunity for each person to participate in society, professions, the job market, and commerce. It means looking for less-burdensome alternatives when accomplishing important objectives. It means balancing competing interests so that as many people as possible can live as equal citizens according to their deepest values and needs.
Such balancing is not a precise science. No one can have all they want. It requires dialogue, understanding, goodwill, principled stances, hard compromises, and a willingness to adjust so that our laws and communities make space for everyone. It requires—as the Savior required—that we be peacemakers.
Conclusion
This is a tall order, to be sure. I know some believe religious freedom should never have to compromise. I know some believe we should stand and fight on every front. Such feelings are visceral and emotional, and I understand them. But if we do that—if we merely give vent to our emotions—in the current cultural environment, we risk losing everything. And we risk failing to follow the example of Christ. Wisdom, fairness, and love for our religious freedoms require that we engage with our fellow citizens, reaching across serious cultural divides, and find common ground so that everyone can live together in freedom and peace. I hope we will all do our part to achieve that lofty goal. Thank you.`

